#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <sdns.h>
#include <sdns_print.h>
#include <sdns_json.h>
#include <time.h>

/*
 *
 * the packet generated by 'dig @1.1.1.1 google.com +nsid +qr +cookie'
 * ; <<>> DiG 9.18.24-0ubuntu5-Ubuntu <<>> @1.1.1.1 google.com +nsid +qr +cookie
 * ; (1 server found)
 * ;; global options: +cmd
 * ;; Sending:
 * ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 31150
 * ;; flags: rd ad; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1
 * 
 * ;; OPT PSEUDOSECTION:
 * ; EDNS: version: 0, flags:; udp: 1232
 * ; NSID:
 * ; COOKIE: ba06926f5e84d8bf
 * ;; QUESTION SECTION:
 * ;google.com.			IN	A
 * 
 * ;; QUERY SIZE: 55
 * 
 * ;; Got answer:
 * ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 31150
 * ;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
 * 
 * ;; OPT PSEUDOSECTION:
 * ; EDNS: version: 0, flags:; udp: 1232
 * ; NSID: 34 39 6d 32 36 39 ("49m269")
 * ;; QUESTION SECTION:
 * ;google.com.			IN	A
 * 
 * ;; ANSWER SECTION:
 * google.com.		261	IN	A	142.250.200.206
 * 
 * ;; Query time: 23 msec
 * ;; SERVER: 1.1.1.1#53(1.1.1.1) (UDP)
 * ;; WHEN: Mon Jun 24 20:13:33 CEST 2024
 * ;; MSG SIZE  rcvd: 65
 *
 */


int main(int argc, char ** argv){
    srand(time(NULL));
    sdns_context * dns_ctx = sdns_init_context();
    if (NULL == dns_ctx){
        fprintf(stderr, "Can not initialize the DNS context...\n");
        return 1;
    }
    
    char packet_bytes[] = {
      0x97, 0x58, 0x01, 0x20, 0x00, 0x01, 0x00, 0x00,
      0x00, 0x00, 0x00, 0x01, 0x06, 0x67, 0x6f, 0x6f,
      0x67, 0x6c, 0x65, 0x03, 0x63, 0x6f, 0x6d, 0x00,
      0x00, 0x01, 0x00, 0x01, 0x00, 0x00, 0x29, 0x04,
      0xd0, 0x00, 0x00, 0x00, 0x00, 0x00, 0x10, 0x00,
      0x03, 0x00, 0x00, 0x00, 0x0a, 0x00, 0x08, 0x0a,
      0x6a, 0xd7, 0x62, 0x98, 0xaa, 0x5a, 0x2a
    };




    dns_ctx->raw = packet_bytes;
    dns_ctx->raw_len = sizeof(packet_bytes);
    int res = sdns_from_wire(dns_ctx);
    if (res == 0)
        sdns_neat_print_dns(dns_ctx);
    char *dmp = sdns_json_dns_string(dns_ctx);
    fprintf(stdout, "%s\n", dmp);
    free(dmp);
    dns_ctx->raw = NULL;
    sdns_free_context(dns_ctx);
    return 0;
}
