#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <sdns.h>
#include <sdns_print.h>
#include <sdns_json.h>
#include <time.h>
#include <assert.h>


int main(int argc, char ** argv){
    srand(time(NULL));
    sdns_context * dns_ctx = sdns_init_context();
    if (NULL == dns_ctx){
        fprintf(stderr, "Can not initialize the DNS context...\n");
        return 1;
    }
    /* 
     * Multi-answer response: yahoo.com A with ID = 32630 (0x7f76)
     *
     * DNS response generated by:
     *   dig +noedns +nocookie A yahoo.com @1.1.1.1
     *
     * Packet contains:
     * - 1 question
     * - 6 A record answers
     * - name compression using pointer 0xc00c
     * - identical TTL (1751 seconds) for all answers
     *
     * All answer NAME fields point back to the original QNAME.
     */
    char packet_bytes[] = {
        /* ================= DNS HEADER ================= */
        0x7f, 0x76,             /* ID = 0x7f76 = 32630 */
        0x81, 0x80,             /* Flags: QR=1, Opcode=0, RD=1, RA=1, RCODE=0 */
        0x00, 0x01,             /* QDCOUNT = 1 */
        0x00, 0x06,             /* ANCOUNT = 6 */
        0x00, 0x00,             /* NSCOUNT = 0 */
        0x00, 0x00,             /* ARCOUNT = 0 */

        /* ================= QUESTION ================= */
        0x05, 'y','a','h','o','o',
        0x03, 'c','o','m',
        0x00,                   /* QNAME = yahoo.com. */
        0x00, 0x01,             /* QTYPE = A */
        0x00, 0x01,             /* QCLASS = IN */

        /* ================= ANSWER 1 ================= */
        0xc0, 0x0c,             /* NAME = pointer to offset 12 (yahoo.com.) */
        0x00, 0x01,             /* TYPE = A */
        0x00, 0x01,             /* CLASS = IN */
        0x00, 0x00, 0x06, 0xd7, /* TTL = 1751 seconds */
        0x00, 0x04,             /* RDLENGTH = 4 */
        0x4a, 0x06, 0xe7, 0x15, /* RDATA = 74.6.231.21 */

        /* ================= ANSWER 2 ================= */
        0xc0, 0x0c,             /* NAME = pointer to yahoo.com. */
        0x00, 0x01,             /* TYPE = A */
        0x00, 0x01,             /* CLASS = IN */
        0x00, 0x00, 0x06, 0xd7, /* TTL = 1751 seconds */
        0x00, 0x04,             /* RDLENGTH = 4 */
        0x62, 0x89, 0x0b, 0xa4, /* RDATA = 98.137.11.164 */

        /* ================= ANSWER 3 ================= */
        0xc0, 0x0c,             /* NAME = pointer to yahoo.com. */
        0x00, 0x01,             /* TYPE = A */
        0x00, 0x01,             /* CLASS = IN */
        0x00, 0x00, 0x06, 0xd7, /* TTL = 1751 seconds */
        0x00, 0x04,             /* RDLENGTH = 4 */
        0x4a, 0x06, 0x8f, 0x1a, /* RDATA = 74.6.143.26 */

        /* ================= ANSWER 4 ================= */
        0xc0, 0x0c,             /* NAME = pointer to yahoo.com. */
        0x00, 0x01,             /* TYPE = A */
        0x00, 0x01,             /* CLASS = IN */
        0x00, 0x00, 0x06, 0xd7, /* TTL = 1751 seconds */
        0x00, 0x04,             /* RDLENGTH = 4 */
        0x4a, 0x06, 0x8f, 0x19, /* RDATA = 74.6.143.25 */

        /* ================= ANSWER 5 ================= */
        0xc0, 0x0c,             /* NAME = pointer to yahoo.com. */
        0x00, 0x01,             /* TYPE = A */
        0x00, 0x01,             /* CLASS = IN */
        0x00, 0x00, 0x06, 0xd7, /* TTL = 1751 seconds */
        0x00, 0x04,             /* RDLENGTH = 4 */
        0x62, 0x89, 0x0b, 0xa3, /* RDATA = 98.137.11.163 */

        /* ================= ANSWER 6 ================= */
        0xc0, 0x0c,             /* NAME = pointer to yahoo.com. */
        0x00, 0x01,             /* TYPE = A */
        0x00, 0x01,             /* CLASS = IN */
        0x00, 0x00, 0x06, 0xd7, /* TTL = 1751 seconds */
        0x00, 0x04,             /* RDLENGTH = 4 */
        0x4a, 0x06, 0xe7, 0x14  /* RDATA = 74.6.231.20 */
    };
   
    dns_ctx->raw = packet_bytes;
    dns_ctx->raw_len = sizeof(packet_bytes);
    int res = sdns_from_wire(dns_ctx);
    assert(res == 0);
    char * dmp = sdns_json_dns_string(dns_ctx);
    fprintf(stdout, "%s\n", dmp);
    free(dmp);
    dns_ctx->raw = NULL;
    sdns_free_context(dns_ctx);
    return 0;
}
