#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <sdns.h>
#include <sdns_print.h>
#include <sdns_json.h>
#include <time.h>
#include <assert.h>
/*
 * Compile: cd .. && make with-json && cd test && gcc -o test test3.c -I../include -L../bin -lsdns -ljansson && ./test
 * the packet generated by the **response** of the 'dig @1.1.1.1 google.com +nsid +qr +cookie'
 * here is the wireshark output:
 *
 * Domain Name System (response)
 *   Transaction ID: 0x79ae
 *   Flags: 0x8180 Standard query response, No error
 *       1... .... .... .... = Response: Message is a response
 *       .000 0... .... .... = Opcode: Standard query (0)
 *       .... .0.. .... .... = Authoritative: Server is not an authority for domain
 *       .... ..0. .... .... = Truncated: Message is not truncated
 *       .... ...1 .... .... = Recursion desired: Do query recursively
 *       .... .... 1... .... = Recursion available: Server can do recursive queries
 *       .... .... .0.. .... = Z: reserved (0)
 *       .... .... ..0. .... = Answer authenticated: Answer/authority portion was not authenticated by the server
 *       .... .... ...0 .... = Non-authenticated data: Unacceptable
 *       .... .... .... 0000 = Reply code: No error (0)
 *   Questions: 1
 *   Answer RRs: 1
 *   Authority RRs: 0
 *   Additional RRs: 1
 *   Queries
 *       google.com: type A, class IN
 *           Name: google.com
 *           [Name Length: 10]
 *           [Label Count: 2]
 *           Type: A (1) (Host Address)
 *           Class: IN (0x0001)
 *   Answers
 *       google.com: type A, class IN, addr 142.250.200.206
 *           Name: google.com
 *           Type: A (1) (Host Address)
 *           Class: IN (0x0001)
 *           Time to live: 261 (4 minutes, 21 seconds)
 *           Data length: 4
 *           Address: 142.250.200.206
 *   Additional records
 *       <Root>: type OPT
 *           Name: <Root>
 *           Type: OPT (41)
 *           UDP payload size: 1232
 *           Higher bits in extended RCODE: 0x00
 *           EDNS0 version: 0
 *           Z: 0x0000
 *               0... .... .... .... = DO bit: Cannot handle DNSSEC security RRs
 *               .000 0000 0000 0000 = Reserved: 0x0000
 *           Data length: 10
 *           Option: NSID - Name Server Identifier
 *               Option Code: NSID - Name Server Identifier (3)
 *               Option Length: 6
 *               Option Data: 34396d323639
 *   [Request In: 656]
 *   [Time: 0.023001766 seconds]
 *
 */


int main(int argc, char ** argv){
    srand(time(NULL));
    sdns_context * dns_ctx = sdns_init_context();
    if (NULL == dns_ctx){
        fprintf(stderr, "Can not initialize the DNS context...\n");
        return 1;
    }
    char packet_bytes[] = {
      0x79, 0xae, 0x81, 0x80, 0x00, 0x01, 0x00, 0x01,
      0x00, 0x00, 0x00, 0x01, 0x06, 0x67, 0x6f, 0x6f,
      0x67, 0x6c, 0x65, 0x03, 0x63, 0x6f, 0x6d, 0x00,
      0x00, 0x01, 0x00, 0x01, 0xc0, 0x0c, 0x00, 0x01,
      0x00, 0x01, 0x00, 0x00, 0x01, 0x05, 0x00, 0x04,
      0x8e, 0xfa, 0xc8, 0xce, 0x00, 0x00, 0x29, 0x04,
      0xd0, 0x00, 0x00, 0x00, 0x00, 0x00, 0x0a, 0x00,
      0x03, 0x00, 0x06, 0x34, 0x39, 0x6d, 0x32, 0x36,
      0x39
    };

    dns_ctx->raw = packet_bytes;
    dns_ctx->raw_len = sizeof(packet_bytes);
    int res = sdns_from_wire(dns_ctx);
    assert(res == 0);
    char *dmp = sdns_json_dns_string(dns_ctx);
    fprintf(stdout, "%s\n", dmp);
    free(dmp);
    dns_ctx->raw = NULL;
    sdns_free_context(dns_ctx);
    return 0;
}
