#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <sdns.h>
#include <sdns_print.h>
#include <sdns_json.h>
#include <time.h>
#include <assert.h>
/*
 *
 * the packet generated by 'dig @1.1.1.1 yahoo.com +nsid +qr +cookie soa'
 * wireshark output:
 * Domain Name System (response)
 *  Transaction ID: 0x8d80
 *  Flags: 0x8180 Standard query response, No error
 *      1... .... .... .... = Response: Message is a response
 *      .000 0... .... .... = Opcode: Standard query (0)
 *      .... .0.. .... .... = Authoritative: Server is not an authority for domain
 *      .... ..0. .... .... = Truncated: Message is not truncated
 *      .... ...1 .... .... = Recursion desired: Do query recursively
 *      .... .... 1... .... = Recursion available: Server can do recursive queries
 *      .... .... .0.. .... = Z: reserved (0)
 *      .... .... ..0. .... = Answer authenticated: Answer/authority portion was not authenticated by the server
 *      .... .... ...0 .... = Non-authenticated data: Unacceptable
 *      .... .... .... 0000 = Reply code: No error (0)
 *  Questions: 1
 *  Answer RRs: 1
 *  Authority RRs: 0
 *  Additional RRs: 1
 *  Queries
 *      yahoo.com: type SOA, class IN
 *          Name: yahoo.com
 *          [Name Length: 9]
 *          [Label Count: 2]
 *          Type: SOA (6) (Start Of a zone of Authority)
 *          Class: IN (0x0001)
 *  Answers
 *      yahoo.com: type SOA, class IN, mname ns1.yahoo.com
 *          Name: yahoo.com
 *          Type: SOA (6) (Start Of a zone of Authority)
 *          Class: IN (0x0001)
 *          Time to live: 533 (8 minutes, 53 seconds)
 *          Data length: 49
 *          Primary name server: ns1.yahoo.com
 *          Responsible authority's mailbox: hostmaster.yahoo-inc.com
 *          Serial Number: 2024062801
 *          Refresh Interval: 3600 (1 hour)
 *          Retry Interval: 300 (5 minutes)
 *          Expire limit: 1814400 (21 days)
 *          Minimum TTL: 600 (10 minutes)
 *  Additional records
 *      <Root>: type OPT
 *          Name: <Root>
 *          Type: OPT (41) 
 *          UDP payload size: 1232
 *          Higher bits in extended RCODE: 0x00
 *          EDNS0 version: 0
 *          Z: 0x0000
 *              0... .... .... .... = DO bit: Cannot handle DNSSEC security RRs
 *              .000 0000 0000 0000 = Reserved: 0x0000
 *          Data length: 10
 *          Option: NSID - Name Server Identifier
 *              Option Code: NSID - Name Server Identifier (3)
 *              Option Length: 6
 *              Option Data: 3537376d3438
 *  [Request In: 5081]
 *  [Time: 0.022053616 seconds]

 */


int main(int argc, char ** argv){
    srand(time(NULL));
    sdns_context * dns_ctx = sdns_init_context();
    if (NULL == dns_ctx){
        fprintf(stderr, "Can not initialize the DNS context...\n");
        return 1;
    }
    char packet_bytes[] = {
      0x8d, 0x80, 0x81, 0x80, 0x00, 0x01, 0x00, 0x01,
      0x00, 0x00, 0x00, 0x01, 0x05, 0x79, 0x61, 0x68,
      0x6f, 0x6f, 0x03, 0x63, 0x6f, 0x6d, 0x00, 0x00,
      0x06, 0x00, 0x01, 0xc0, 0x0c, 0x00, 0x06, 0x00,
      0x01, 0x00, 0x00, 0x02, 0x15, 0x00, 0x31, 0x03,
      0x6e, 0x73, 0x31, 0xc0, 0x0c, 0x0a, 0x68, 0x6f,
      0x73, 0x74, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72,
      0x09, 0x79, 0x61, 0x68, 0x6f, 0x6f, 0x2d, 0x69,
      0x6e, 0x63, 0xc0, 0x12, 0x78, 0xa4, 0xbf, 0x51,
      0x00, 0x00, 0x0e, 0x10, 0x00, 0x00, 0x01, 0x2c,
      0x00, 0x1b, 0xaf, 0x80, 0x00, 0x00, 0x02, 0x58,
      0x00, 0x00, 0x29, 0x04, 0xd0, 0x00, 0x00, 0x00,
      0x00, 0x00, 0x0a, 0x00, 0x03, 0x00, 0x06, 0x35,
      0x37, 0x37, 0x6d, 0x34, 0x38
    };


    dns_ctx->raw = packet_bytes;
    dns_ctx->raw_len = sizeof(packet_bytes);
    int res = sdns_from_wire(dns_ctx);
    assert (res == 0);
    char *dmp = sdns_json_dns_string(dns_ctx);
    fprintf(stdout, "%s\n", dmp);
    free(dmp);
    dns_ctx->raw = NULL;
    sdns_free_context(dns_ctx);
    return 0;
}
