var searchData=
[
  ['sdns_5fcontext_0',['sdns_context',['../structsdns__context.html',1,'']]],
  ['sdns_5fheader_1',['sdns_header',['../structsdns__header.html',1,'']]],
  ['sdns_5fmessage_2',['sdns_message',['../structsdns__message.html',1,'']]],
  ['sdns_5fopt_5fttl_3',['sdns_opt_ttl',['../structsdns__opt__ttl.html',1,'']]],
  ['sdns_5fquestion_4',['sdns_question',['../structsdns__question.html',1,'']]],
  ['sdns_5frr_5fa_5',['sdns_rr_A',['../structsdns__rr__A.html',1,'']]],
  ['sdns_5frr_5faaaa_6',['sdns_rr_AAAA',['../structsdns__rr__AAAA.html',1,'']]],
  ['sdns_5frr_5fcname_7',['sdns_rr_CNAME',['../structsdns__rr__CNAME.html',1,'']]],
  ['sdns_5frr_5fhinfo_8',['sdns_rr_HINFO',['../structsdns__rr__HINFO.html',1,'']]],
  ['sdns_5frr_5fl32_9',['sdns_rr_L32',['../structsdns__rr__L32.html',1,'']]],
  ['sdns_5frr_5fl64_10',['sdns_rr_L64',['../structsdns__rr__L64.html',1,'']]],
  ['sdns_5frr_5flp_11',['sdns_rr_LP',['../structsdns__rr__LP.html',1,'']]],
  ['sdns_5frr_5fmx_12',['sdns_rr_MX',['../structsdns__rr__MX.html',1,'']]],
  ['sdns_5frr_5fnid_13',['sdns_rr_NID',['../structsdns__rr__NID.html',1,'']]],
  ['sdns_5frr_5fns_14',['sdns_rr_NS',['../structsdns__rr__NS.html',1,'']]],
  ['sdns_5frr_5fopt_5fede_15',['sdns_rr_OPT_EDE',['../structsdns__rr__OPT__EDE.html',1,'']]],
  ['sdns_5frr_5fptr_16',['sdns_rr_PTR',['../structsdns__rr__PTR.html',1,'']]],
  ['sdns_5frr_5frrsig_17',['sdns_rr_RRSIG',['../structsdns__rr__RRSIG.html',1,'']]],
  ['sdns_5frr_5fsoa_18',['sdns_rr_SOA',['../structsdns__rr__SOA.html',1,'']]],
  ['sdns_5frr_5fsrv_19',['sdns_rr_SRV',['../structsdns__rr__SRV.html',1,'']]],
  ['sdns_5frr_5furi_20',['sdns_rr_URI',['../structsdns__rr__URI.html',1,'']]]
];
