name: C-build-and-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: use repo content
    - uses: action/checkout@main

    - name: Install dependencies
      run: 
        sudo apt install -y libjansson-dev
        pip3 install jsoncomparison

    - name: Make
      run: make
