name: C-build-and-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: use repo content
      uses: actions/checkout@main
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: 
        sudo apt install -y libjansson-dev
    - name: Install python package
      run:
        python -m pip install jsoncomparison

    - name: Make
      run: make
    - name: Run tests without valgrind
      run: cd test && ./sdns_test.sh
